### ISSUE TITLE
Some people don't see the maps

### ISSUE THREAD

**Issue by scisco** [developmentseed/work.vote#16]

**Comment by DylanMoriarty** [comment]
Testing this in Browserify, the JS seems to be failing in IE11.

**Comment by DylanMoriarty** [comment]
~Similarly, it seems like the map doesn't want to zoom in when loaded on Firefox.~

Looking at mapbox maps on their own site, it looks like they don't support the 'pinch' style of zooming on firefox. I'm guessing that because we're drawing a layer on top of the map in the JS with an event on clicking, that's nullifying the typical 'click to zoom' bit.

Will look into whether that can be re-added with some JS, but will add on zoom controls, as those really should be there anyway.

**Comment by scisco** [comment]
Fixed
